name: Windows Compile

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          cmake -S . -B "build/x64" -G "Visual Studio 17 2022" -T v143 -A x64 -DCMAKE_BUILD_TYPE=Release
          cmake --build ./build/x64
      - name: Create Package
        run: |
          (cd build/x64 && cpack)
          cd ..
          mv _packages/*.zip _packages/ultra-viewer-windows.zip
          Expand-Archive -Path _packages/ultra-viewer-windows.zip -DestinationPath ultra-viewer-windows
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: ultra-viewer-windows
          path: ultra-viewer-windows